### PR TITLE
Add details on NCCL topology & performance

### PR DESCRIPTION
**Pull request by Edenzzzz**
Hi Chenyang, 
I added some of my own understanding. I've tried translating to English, but ChatGPT 4o won't translate more than a paragraph  :(.  I will try Kimi later.
I feel we can have an auto-translated English version for each of the READMEs, especially the SGLang code walk through, to help new developers (I'm one of them still learning SGLang's code structure). 

Thanks!

### CODE REVIEW

**Review by zhaochenyang20 — APPROVED** [review]
Thanks a lot!

**Comment by zhaochenyang20** [comment]
@Edenzzzz BTW, would you mind sharing your WeChat with me? We can discuss the code walk-through documents later, which is pretty important.

**Comment by Edenzzzz** [comment]
> @Edenzzzz BTW, would you mind sharing your WeChat with me? We can discuss the code walk-through documents later, which is pretty important.

@zhaochenyang20 Sure! (Though I often use Wechat for chitchats and slack for work :) ). I'll try to help but can have fluctuating availability due to courses etc. :) 
Wechat: a1905118069

**Comment by Edenzzzz** [comment]
Kimi's translation is kind of stiff 
image

**Comment by zhaochenyang20** [comment]
We gonna make important part into English, I am sure 😂 @Edenzzzz

**Comment by zhaochenyang20** [comment]
@Edenzzzz Are you sure your ID is right? Could you try mine: 

learnAIcantSaveChina

**Pull request merged**
