### PR TITLE
[Docs]: Add Chinese readme

### PR DESCRIPTION
**Pull request by JamesSand**
According to #3 , thsi PR 
1. added a Chinese version of Code Walk Through of SGLang.
2. added a pointer to Chinese readme  in original English readme.

### CODE REVIEW

**Comment by zhaochenyang20** [comment]
@JamesSand Please also change the main readme at the root dir. Nice job anyway!

**Comment by JamesSand** [comment]
> @JamesSand Please also change the main readme at the root dir. Nice job anyway!

Sure. I will do this

**Comment by JamesSand** [comment]
Hi @zhaochenyang20 , it seems the [the main readme in root dir](https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/blob/main/README.md) is already Chinese. So which one do you mean for "the main readme at the root dir"?

**Comment by JamesSand** [comment]
I think you mean the pointer to the Chinese readme in the English readme. I have already added this feature [here](https://github.com/JamesSand/Awesome-ML-SYS-Tutorial/blob/b1ce63242e595e61a2670b985973e2ae57da45ae/sglang/code-walk-through/readme.md?plain=1#L3)

**Review by zhaochenyang20 — APPROVED** [review]

**Pull request merged**
